unit EntitiesU;

interface

uses
  MVCFramework.Serializer.Commons,
  MVCFramework.ActiveRecord,
  MVCFramework.Nullables,
  MVCFramework.Commons,
  MVCFramework.SQLGenerators.MySQL,
  System.Generics.Collections;

type
  {Entity Base}
  TEntityBase = class abstract(TMVCActiveRecord)
  protected
    [MVCTableField('ID', [foPrimaryKey, foAutoGenerated])]
    fID: Integer;
  public
    property ID: Integer read fID write fID;
  end;

  {Person Entity Base}
  TPersonEntityBase = class abstract(TEntityBase)
  private
    [MVCTableField('DOB')]
    fDateOfBirth: TDate;
  public
    property DateOfBirth: TDate read fDateOfBirth write fDateOfBirth;
  end;

  {User Entity}
  [MVCNameCase(ncSnakeCase)]
  [MVCTable('user')]
  TUser = class(TEntityBase)
  private
    [MVCTableField('DELETED')]
    fDeleted: boolean;
    [MVCTableField('EMAIL')]
    fEmail: string;
    [MVCTableField('LAST_LOGIN')]
    fLastLogin: NullableTDateTime;
  public
    [MVCDoNotSerialize]
    [MVCDoNotDeSerialize]
    property Deleted: boolean read fDeleted write fDeleted;
    property Email: string read fEmail write fEmail;
    [MVCDoNotDeSerialize]
    property LastLogin: NullableTDateTime read fLastLogin write fLastLogin;
    //constructor Create; override;
  end;

  {TUserWithPassword Entity}
  [MVCNameCase(ncSnakeCase)]
  [MVCTable('user')]
  [MVCEntityActions([eaCreate, eaUpdate, eaRetrieve])]
  TUserWithPassword = class(TUser)
  private
    { this field is not retrieve and not stored from/to the database }
    fPassword: string;
    [MVCTableField('PWD', [foWriteOnly])]
    fHashedPwd: string;
    [MVCTableField('SALT', [foWriteOnly])]
    fSalt: string;
    fIterationsCount: Integer;
    function GetPassword: string;
    procedure SetPassword(const NewPassword: string);
  protected
    procedure OnBeforeInsertOrUpdate; override;
    procedure OnValidation(const EntityAction: TMVCEntityAction); override;
  public
    [MVCDoNotSerialize]
    [MVCNameAs('pwd')]
    property Password: string read GetPassword write SetPassword;
  end;

  {Customer Entity}
  [MVCNameCase(ncSnakeCase)]
  [MVCTable('customer')]
  TCustomer = class(TPersonEntityBase)
  private
    [MVCTableField('FIRST_NAME')]
    fFirstName: string;
    [MVCTableField('LAST_NAME')]
    fLastName: string;
    [MVCTableField('NOTE')]
    fNote: NullableString;
  public
    property FirstName: string read fFirstName write fFirstName;
    property LastName: string read fLastName write fLastName;
    property Note: NullableString read fNote write fNote;
  end;

  {Book Ref Entity}
  [MVCNameCase(ncSnakeCase)]
  [MVCTable('book')]
  TBookRef = class(TEntityBase)
  private
    fLinks: TMVCStringDictionary;
    [MVCTableField('PUB_YEAR')]
    fPubYear: NullableUInt16;
    [MVCTableField('TITLE')]
    fTitle: string;
    function GetLinks: TMVCStringDictionary;
  public
    property Links: TMVCStringDictionary read GetLinks;
    property PubYear: NullableUInt16 read fPubYear write fPubYear;
    property Title: string read fTitle write fTitle;
  end;

  {Author Entity}
  [MVCNameCase(ncSnakeCase)]
  [MVCTable('author')]
  TAuthor = class(TPersonEntityBase)
  private
    fBooks: TEnumerable<TBookRef>;
    [MVCTableField('FULL_NAME')]
    fFullName: string;
    function GetBooks: TEnumerable<TBookRef>;
  public
    property FullName: string read fFullName write fFullName;
    {book is an enumerable of TBookRef, a lightweight version of TBook}
    property Books: TEnumerable<TBookRef> read GetBooks;
  end;

  {Book Entity}
  [MVCNameCase(ncSnakeCase)]
  [MVCTable('book')]
  TBook = class(TEntityBase)
  private
    [MVCTableField('AUTHOR_ID')]
    fAuthorID: Integer;
    [MVCTableField('PUB_YEAR')]
    fPubYear: NullableUInt16;
    [MVCTableField('TITLE')]
    fTitle: string;
    procedure OnValidation(const EntityAction: TMVCEntityAction); override;
  public
    property AuthorID: Integer read fAuthorID write fAuthorID;
    property PubYear: NullableUInt16 read fPubYear write fPubYear;
    property Title: string read fTitle write fTitle;
  end;

  {Book and Author}
  [MVCNameCase(ncSnakeCase)]
  TBookAndAuthor = class(TEntityBase)
  private
    fAuthor: string;
    fAuthorID: Integer;
    fPubYear: NullableUInt16;
    fTitle: string;
  public
    property Author: string read fAuthor write fAuthor;
    property AuthorID: Integer read fAuthorID write fAuthorID;
    property PubYear: NullableUInt16 read fPubYear write fPubYear;
    property Title: string read fTitle write fTitle;
  end;

  {Lending Entity}
  [MVCNameCase(ncSnakeCase)]
  [MVCTable('lending')]
  TLending = class(TEntityBase)
  private
    [MVCTableField('BOOK_ID')]
    fBookID: integer;
    [MVCTableField('CUSTOMER_ID')]
    fCustomerID: Integer;
    [MVCTableField('LENDING_END')]
    fLendingEnd: NullableTDateTime;
    [MVCTableField('LENDING_END_USER_ID')]
    fLendingEndUserID: NullableInt64;
    [MVCTableField('LENDING_START')]
    fLendingStart: NullableTDateTime;
    [MVCTableField('LENDING_START_USER_ID')]
    fLendingStartUserID: NullableInt64;
  public
    property BookID: Integer
      read fBookID write fBookID;
    property CustomerID: Integer
      read fCustomerID write fCustomerID;
    property LendingEnd: NullableTDateTime
      read fLendingEnd write fLendingEnd;
    property LendingEndUserID: NullableInt64
      read fLendingEndUserID write fLendingEndUserID;
    property LendingStart: NullableTDateTime
      read fLendingStart write fLendingStart;
    property LendingStartUserID: NullableInt64
      read fLendingStartUserID write fLendingStartUserID;
  end;

implementation

uses
  System.SysUtils, CommonsU, AuthServiceU, System.Math;

{ TBookRef }
function TBookRef.GetLinks: TMVCStringDictionary;
var
  lDict: TMVCStringDictionary;
begin
  lDict := TMVCStringDictionary.Create;
  lDict.Add(HATEOAS._TYPE, TMVCMediaType.APPLICATION_JSON);
  lDict.Add(HATEOAS.HREF, '/api/books/' + IntToStr(Self.ID));
  lDict.Add(HATEOAS.REL, 'self');
  Result := lDict;
end;

{ TAuthor }
function TAuthor.GetBooks: TEnumerable<TBookRef>;
begin
  if fBooks = nil then
  begin
    fBooks := TMVCActiveRecord.Where<TBookRef>('author_id = ?', [ID]);
    AddChildren(fBooks);
  end;
  Result := fBooks;
end;

{ TUserWithPassword }

function TUserWithPassword.GetPassword: string;
begin
  Result := 'password is hidden';
end;

procedure TUserWithPassword.OnBeforeInsertOrUpdate;
begin
  inherited;
  fSalt := TGUID.NewGuid.ToString;
  fIterationsCount := TSysConst.PASSWORD_HASHING_ITERATION_COUNT;
  fHashedPwd := GetPasswordHash(fSalt, fIterationsCount,
    TSysConst.PASSWORD_KEY_SIZE, fPassword);
end;

procedure TUserWithPassword.OnValidation(const EntityAction: TMVCEntityAction);
begin
  inherited;
  if fPassword.IsEmpty then
  begin
    raise Exception.Create('Password cannot be empty');
  end;
end;

procedure TUserWithPassword.SetPassword(const NewPassword: string);
begin
  fPassword := NewPassword;
end;


{ TBook }

procedure TBook.OnValidation(const EntityAction: TMVCEntityAction);
begin
  inherited;

end;

end.
