unit EntitiesVCLU;

interface

uses
  MVCFramework.ActiveRecord,
  MVCFramework.Nullables;

type
  [MVCTable('customer')]
  TCustomer = class(TMVCActiveRecord)
  private
    [MVCTableField('ID', [foPrimaryKey, foAutoGenerated])]
    fID: Integer;
    [MVCTableField('FIRST_NAME')]
    fFirstName: string;
    [MVCTableField('LAST_NAME')]
    fLastName: string;
    [MVCTableField('DOB')]
    fDateOfBirth: TDate;
    [MVCTableField('NOTE')]
    fNote: NullableString;
  protected
    function GetFullName: string;
    procedure OnBeforeInsertOrUpdate; override;
  public
    property ID: Integer read fID write fID;
    property FirstName: string read fFirstName write fFirstName;
    property LastName: string read fLastName write fLastName;
    property DateOfBirth: TDate read fDateOfBirth write fDateOfBirth;
    property Note: NullableString read fNote write fNote;
    property FullName: string read GetFullName;
  end;

implementation

uses
  System.SysUtils, MVCFramework.SQLGenerators.MySQL;

function TCustomer.GetFullName: string;
begin
  Result := fFirstName + ' ' + fLastName;
end;

procedure TCustomer.OnBeforeInsertOrUpdate;
begin
  inherited;
  if fFirstName.Trim.IsEmpty or fLastName.Trim.IsEmpty then
  begin
    raise Exception.Create('First name and last name is required');
  end;

end;


end.

